# Generated by Django 5.1.4 on 2026-07-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Bloklangan"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False, verbose_name="Telefon tasdiqlangan"
            ),
        ),
    ]
