# Generated by Django 5.1.4 on 2026-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_grandfather_verified_barbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="audience_pref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("men", "Erkaklar"),
                    ("women", "Ayollar"),
                    ("all", "Barchasi"),
                ],
                default=None,
                max_length=10,
                null=True,
                verbose_name="Auditoriya tanlovi",
            ),
        ),
    ]
