# Generated by Django 5.1.4 on 2026-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_audience_pref"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_reengaged_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
