# Generated by Django 5.1.4 on 2026-06-11 12:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Flaticon class nomi", max_length=60
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat kategoriyasi",
                "verbose_name_plural": "Xizmat kategoriyalari",
                "db_table": "service_categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Daqiqalarda",
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="Davomiyligi (daqiqa)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Narxi (so'm)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "barbers",
                    models.ManyToManyField(
                        blank=True, related_name="services", to="shops.barberprofile"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="shops.shop",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "db_table": "services",
                "ordering": ["order", "name"],
            },
        ),
    ]
