# Generated by Django 5.1.4 on 2026-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="support/%Y/%m/",
                verbose_name="Biriktirilgan fayl",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True, verbose_name="Xabar"),
        ),
    ]
