# Generated by Django 5.1.4 on 2026-06-11 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("address", models.TextField(verbose_name="Manzil")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "telegram_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Portfolio uchun Telegram kanal ID (masalan: @mychanel yoki -1001234567890)",
                        max_length=100,
                        verbose_name="Telegram kanal ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/covers/",
                        verbose_name="Muqova",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["owner", "barber"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon",
                "verbose_name_plural": "Salonlar",
                "db_table": "shops",
            },
        ),
        migrations.CreateModel(
            name="BarberProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tajriba (yil)"
                    ),
                ),
                (
                    "slot_duration",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Bir bronlash uchun daqiqalar soni",
                        verbose_name="Slot davomiyligi (daqiqa)",
                    ),
                ),
                (
                    "is_accepting_bookings",
                    models.BooleanField(
                        default=True, verbose_name="Bronlash qabul qilmoqda"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartibi"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["barber", "owner"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbers",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sartarosh profili",
                "verbose_name_plural": "Sartarosh profillari",
                "db_table": "barber_profiles",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Dushanba"),
                            (1, "Seshanba"),
                            (2, "Chorshanba"),
                            (3, "Payshanba"),
                            (4, "Juma"),
                            (5, "Shanba"),
                            (6, "Yakshanba"),
                        ],
                        verbose_name="Hafta kuni",
                    ),
                ),
                ("open_time", models.TimeField(verbose_name="Ochilish vaqti")),
                ("close_time", models.TimeField(verbose_name="Yopilish vaqti")),
                (
                    "is_day_off",
                    models.BooleanField(default=False, verbose_name="Dam olish kuni"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish vaqti",
                "verbose_name_plural": "Ish vaqtlari",
                "db_table": "shop_working_hours",
                "ordering": ["day_of_week"],
                "unique_together": {("shop", "day_of_week")},
            },
        ),
    ]
