# Generated by Django 5.1.4 on 2026-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barberprofile",
            name="specialization",
            field=models.CharField(
                choices=[("men", "Erkaklar"), ("women", "Ayollar"), ("all", "Hammasi")],
                default="all",
                max_length=10,
                verbose_name="Mutaxassislik",
            ),
        ),
    ]
