# Generated by Django 5.1.4 on 2026-07-15 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_add_barber_specialization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopJoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=300, verbose_name="Xabar"),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["barber", "owner"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salonga qo'shilish so'rovi",
                "verbose_name_plural": "Salonga qo'shilish so'rovlari",
                "db_table": "shop_join_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "status"], name="shop_join_r_shop_id_2668af_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("barber", "shop"),
                        name="uniq_pending_join_request",
                    )
                ],
            },
        ),
    ]
