# Generated by Django 5.1.4 on 2026-07-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_shopjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Shahar"),
        ),
    ]
