# Generated by Django 5.1.4 on 2026-07-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shop_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="barberprofile",
            name="rating_avg",
            field=models.FloatField(default=0, verbose_name="O'rtacha baho"),
        ),
        migrations.AddField(
            model_name="barberprofile",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Baholar soni"),
        ),
        migrations.AddField(
            model_name="shop",
            name="rating_avg",
            field=models.FloatField(default=0, verbose_name="O'rtacha baho"),
        ),
        migrations.AddField(
            model_name="shop",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Baholar soni"),
        ),
    ]
