# Generated by Django 5.1.4 on 2026-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_barberprofile_rating_avg_barberprofile_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
