# Generated by Django 5.1.4 on 2026-07-19 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_shop_facebook_url_shop_tiktok_url_shop_youtube_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Shikoyatlar tufayli avtomatik yoki admin tomonidan yashiringan",
                verbose_name="To'xtatilgan (moderatsiya)",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "Soxta / aldov"),
                            ("inappropriate", "Nomaqbul kontent"),
                            ("spam", "Spam"),
                            ("no_show", "Kelmadi / aldadi"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                        verbose_name="Sabab",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("reviewed", "Ko'rib chiqilgan"),
                            ("dismissed", "Rad etilgan"),
                        ],
                        default="open",
                        max_length=12,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shikoyat",
                "verbose_name_plural": "Shikoyatlar",
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "status"], name="reports_shop_id_a7c166_idx"
                    )
                ],
                "unique_together": {("reporter", "shop")},
            },
        ),
    ]
