# Generated by Django 5.1.4 on 2026-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_shop_is_suspended_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="category",
            field=models.CharField(
                choices=[
                    ("men", "Erkaklar saloni"),
                    ("women", "Ayollar (go'zallik) saloni"),
                    ("unisex", "Unisex (aralash)"),
                ],
                default="men",
                help_text="Salon kimga xizmat qiladi (mijoz filtri uchun)",
                max_length=10,
                verbose_name="Salon turi",
            ),
        ),
    ]
