# Generated by Django 5.1.4 on 2026-07-21 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_shop_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sevimli",
                "verbose_name_plural": "Sevimlilar",
                "db_table": "favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"],
                        name="favorites_client__14c42a_idx",
                    )
                ],
                "unique_together": {("client", "shop")},
            },
        ),
    ]
