# Generated by Django 5.1.4 on 2026-06-11 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Sana")),
                ("start_time", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("end_time", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlangan"),
                            ("cancelled", "Bekor qilindi"),
                            ("completed", "Bajarildi"),
                            ("no_show", "Kelmadi"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "client_note",
                    models.TextField(blank=True, verbose_name="Mijoz izohi"),
                ),
                (
                    "barber_note",
                    models.TextField(blank=True, verbose_name="Sartarosh izohi"),
                ),
                ("reminded_1h", models.BooleanField(default=False)),
                ("reminded_24h", models.BooleanField(default=False)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="shops.barberprofile",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bron",
                "verbose_name_plural": "Bronlar",
                "db_table": "appointments",
                "ordering": ["-date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["barber", "date"], name="appointment_barber__a2278d_idx"
                    ),
                    models.Index(
                        fields=["client", "date"], name="appointment_client__8e4290_idx"
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_9fecd6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockedSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Sana")),
                ("start_time", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("end_time", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Sabab"),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_slots",
                        to="shops.barberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloklangan vaqt",
                "verbose_name_plural": "Bloklangan vaqtlar",
                "db_table": "blocked_slots",
                "indexes": [
                    models.Index(
                        fields=["barber", "date"], name="blocked_slo_barber__a8db91_idx"
                    )
                ],
            },
        ),
    ]
