# Generated by Django 5.1.4 on 2026-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminded_5m",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("confirmed", "Tasdiqlangan"),
                    ("cancelled", "Bekor qilindi"),
                    ("completed", "Bajarildi"),
                    ("no_show", "Kelmadi"),
                    ("expired", "Muddati o'tdi"),
                ],
                default="pending",
                max_length=15,
                verbose_name="Holat",
            ),
        ),
    ]
