# Generated by Django 5.1.4 on 2026-07-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_review"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Barcha tanlangan xizmatlar (ko'p xizmat brони)",
                related_name="appointments_multi",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                help_text="Asosiy (birinchi) xizmat",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="services.service",
            ),
        ),
    ]
