# Generated by Django 5.1.4 on 2026-07-20 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_appointment_services_alter_appointment_service"),
        ("shops", "0008_shop_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Sana")),
                ("notified", models.BooleanField(default=False)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="shops.barberprofile",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbat (waitlist)",
                "verbose_name_plural": "Navbatlar (waitlist)",
                "db_table": "waitlist_entries",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["barber", "date", "notified"],
                        name="waitlist_en_barber__c869a3_idx",
                    )
                ],
                "unique_together": {("client", "barber", "date")},
            },
        ),
    ]
