# Generated by Django 5.1.4 on 2026-07-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_waitlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancel_reason",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Bekor qilish sababi"
            ),
        ),
    ]
