# Generated by Django 5.1.4 on 2026-06-11 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_message_id",
                    models.BigIntegerField(verbose_name="Telegram xabar ID"),
                ),
                (
                    "telegram_file_id",
                    models.CharField(max_length=300, verbose_name="Telegram fayl ID"),
                ),
                (
                    "telegram_file_unique_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Unikal fayl ID"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("photo", "Rasm"), ("video", "Video")],
                        default="photo",
                        max_length=10,
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="Izoh")),
                ("thumbnail_file_id", models.CharField(blank=True, max_length=300)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ko'rsatilsin"),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "barber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_posts",
                        to="shops.barberprofile",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_posts",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio post",
                "verbose_name_plural": "Portfolio postlar",
                "db_table": "portfolio_posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"],
                        name="portfolio_p_shop_id_954f7a_idx",
                    ),
                    models.Index(
                        fields=["barber", "is_active"],
                        name="portfolio_p_barber__620a8e_idx",
                    ),
                ],
            },
        ),
    ]
